### PR TITLE
remove preview3 and rc2 dotnet core tests

### PR DESCRIPTION
**Pull request by watashiSHUN**
remove git tests:
[preview3cli](https://github.com/KuduApps/AspNetCorePreview3Cli.git)
[preview3multipleproj](https://github.com/KuduApps/AspNetCorePreview3MultipleProjects.git)
[preview3vs](https://github.com/KuduApps/AspNetCorePreview3VSsln.git)
[yeoman2projects](https://github.com/KuduApps/AspNetCoreRC2Yeoman2Projects.git)
[yeoman](https://github.com/KuduApps/AspNetCoreRC2YeomanProject.git)
[rc2vs](https://github.com/KuduApps/AspNetCoreRC2VisualStudioSln.git)

update git tests:
[mixedproject](https://github.com/KuduApps/AspNetCoreMixedProjects) => latest available preview2 sdk
[preview2](https://github.com/KuduApps/AspNetCorePreview2MultipleProjects) => latest available preview2 sdk
[rc4vs](https://github.com/KuduApps/AspNetCoreRC4WebApiVsSln) => replace the structure of [preview3multipleproj](https://github.com/KuduApps/AspNetCorePreview3MultipleProjects.git)

new git test:
[newyeoman](https://github.com/KuduApps/AspNetCoreYeomanProject) => replace the structure of [yeoman2projects](https://github.com/KuduApps/AspNetCoreRC2Yeoman2Projects.git) and [yeoman](https://github.com/KuduApps/AspNetCoreRC2YeomanProject.git)

[this](https://github.com/Azure/kudu/commit/0e9b61ddccc472722016c054539d33c11852ff43) is the commit after merging to private

### CODE REVIEW

**Comment by watashiSHUN** [comment]
Note to self, remove repositories from kuduapp after test

**Comment by watashiSHUN** [comment]
[preview2](https://github.com/KuduApps/AspNetCorePreview2MultipleProjects) and [mixedproject](https://github.com/KuduApps/AspNetCoreMixedProjects) are removed at https://github.com/Azure/kudu/commit/8273a0230dc9e60c7f0d69a170c48260e3beaa21, when we update to nuget4.3 which no longer supports xproj

**Comment by davidebbo** [comment]
Cool. Just make sure we have decent coverage for the official 1.0, 1.1 and 2.0 versions.

**Comment by watashiSHUN** [comment]
// following tests can break even when there's no code change in `kudu/kuduscript`
1. VS2017 with lib (netstandard + netcore)
a. [1.0](https://github.com/KuduApps/AspNetCore1.0.0VS17WithLib)
b. [1.1](https://github.com/KuduApps/AspNetCore1.1.0VS17WithLib)
c.  [2.0](https://github.com/KuduApps/AspNetCore2.0.0VS17WithLib)

// if above changes passed successfully but following failed --> `kudu/kuduscript` issues
1. [dotnet core cli project](https://github.com/KuduApps/AspNetCore2.0.0Cli) **no ".deployment"**
2. [dotnet core cli project with lib](https://github.com/KuduApps/AspNetCore2.0CliWithLib) **has ".deployment"**
2. [multiple VS projects](https://github.com/KuduApps/AspNetCoreRC4WebApiVsSln) (**not necessary** `dotnet restore xxx.csproj` alone is enough, we needed `nuget restore xxx.sln` since dotnet restore cannot deal with `xxx.xproj`, but that case was removed)
3. [Yeoman](https://github.com/KuduApps/AspNetCoreYeomanProject) (project.json)

**Pull request merged**
