### PR TITLE
fixes issue #2137

### PR DESCRIPTION
**Pull request by watashiSHUN**
continuous deployment with azure function should now install npm packages

### CODE REVIEW

**Comment by davidebbo** [comment]
Looks good. Do you have a matching PR in KuduScript?

**Comment by watashiSHUN** [comment]
projectkudu/KuduScript#53

**Comment by davidebbo** [comment]
Ok, you probably need to update this one to match kuduscript commit. Then :shipit:

**Comment by watashiSHUN** [comment]
merged b5207cb33ce5c46a630e16a19b5ed6ab2088dea0

**Pull request merged**
