### PR TITLE
Use PssCaptureSnapshot for memory dump

### PR DESCRIPTION
**Pull request by pharring**
Use PssCaptureSnapshot for the memory dump feature. This API is what the Snapshot Debugger and procdump use to capture fast snapshots without impacting the running process.

### CODE REVIEW

**Comment by pharring** [comment]
@safihamid @puneet-gupta FYI

**Comment by suwatch** [comment]
Looks good overall.  Have we tested with private site extension?   Also check if we have existing tests that need to be improved to cover this.

**Comment by pharring** [comment]
@suwatch I tested in my own site using DeployPrivateKudu.cmd, if that's what you mean.
There are three unit tests in ProcessApiFacts that have something to do with minidump:
* MiniDumpDeleteOnDisposeTests
* MiniDumpDeleteOnCloseTests
* MiniDumpFreeModeTests
None of them actually tries to dump a process!
I'll see if I can add one that exercises the new code.

**Comment by pharring** [comment]
I added a unit test. I tested 32-bit already. I'll test 64-bit now.

**Comment by suwatch** [comment]
Once done with 64 bits testing - could you?
- Rebase with latest master (you might already have that).
- Rebase to single commit if you can.

I will merge this in.  Let me know if you need help for any of these.

**Comment by pharring** [comment]
I verified that 64-bit snapshot+dump works.

**Comment by pharring** [comment]
@suwatch rebased and squashed. This is ready to merge.

**Pull request merged**
