### PR TITLE
Ruby Site Deployment 

### PR DESCRIPTION
**Pull request by Hamster-Huey**
Add support for detecting ruby sites and running a ruby-specific deployment scenario.

### CODE REVIEW

**Comment by suwatch** [comment]
Mind adding a test as well as a pre-req to be able to run these tests.

**Comment by davidebbo** [comment]
@Hamster-Huey was this ever merged in or still pending?

**Comment by Hamster-Huey** [comment]
@davidebbo Code's been merged, possibly manually I forget, but I see the ruby code in the repo.

**Comment by davidebbo** [comment]
Ok, closing PR then.

**Pull request closed without merging**
