### PR TITLE
Fix for issue #1566

### PR DESCRIPTION
**Pull request by HansOlavS**
Changed method CreateIdleTimeoutException to suggest correct setting 'WEBJOBS_IDLE_TIMEOUT' for increasing the idle timeout.

### CODE REVIEW

**Comment by davidebbo** [comment]
It's not that simple. This is general code that also gets called outside of WebJobs, and in most cases `SCM_COMMAND_IDLE_TIMEOUT` is correct. e.g. during a long git deployment waiting for some operation.

Making the message correct would probably involve passing in the flag name, or something like that. We'd need to look at all the call trees leading to it to see what makes sense.

**Comment by HansOlavS** [comment]
@davidebbo, what about a new method spesifically used from webjobs? That way I won't break anything dependent on the existing method used...

**Comment by mathewc** [comment]
I don't think we should introduce a new method. How about simply updating the message so that it reads like "You may increase SCM_COMMAND_IDLE_TIMEOUT (or WEBJOBS_IDLE_TIMEOUT if this is a web job) to solve the issue". This way we don't need to propagate a flag. I'm not opposed to the flag, if there is a clean way to do it.

**Comment by davidebbo** [comment]
Definitely we don't want to duplicate the entire logic here. I think @mathewc suggestion is the cheapest and safest, even if it is not the 'purest'. :) Let's go with that.

**Comment by HansOlavS** [comment]
Excellent! I thought about that path too, but felt it was a bit too simple (not pure).

**Pull request closed without merging**
