### PR TITLE
Zip push-to-deploy feature

### PR DESCRIPTION
**Pull request by nickwalkmsft**
Addition of zip push-to-deploy.

### CODE REVIEW

**Comment by nickwalkmsft** [comment]
This PR has quite a bit of noise in it, primarily due to the namespaces of a few classes changing. I will send a more focused CodeFlow with notes.

**Comment by davidebbo** [comment]
Why use CodeFlow over GitHub PR system?

**Comment by nickwalkmsft** [comment]
Better diff and commenting experience, ability to prune unimportant changes out of the review. Is there a way to better tailor a PR on GitHub? Maybe I don't know about it. Feel free to comment within the PR as well, I'll read those too.

**Comment by davidebbo** [comment]
Ok, will try to look on CodeFlow.

**Comment by davidebbo** [comment]
@nickwalkmsft can you share the basic API doc? i.e. how do I test this?

**Comment by nickwalkmsft** [comment]
POST a zip file (curl, Postman etc.) to /push-deploy (this will soon be /api/zipdeploy as per Suwat's comment, but I don't have that in yet).

Add ?isAsync=true to do it in the background; the Location header of result will point to the deployment status.

Behavior and results should be what you'd find with any other deployment.

**Comment by davidebbo** [comment]
@nickwalkmsft Instead of piling everything here, I'll open individual issues for anything I find. Starting with #2571.

**Comment by nickwalkmsft** [comment]
New changes and Codeflow sent.

FYI, I found out in CodeFlow that you can diff between two revisions by Ctrl-clicking their tabs.

**Comment by davidebbo** [comment]
So I'm playing tester on this one and letting @suwatch do the CR :)

**Pull request merged**
