### PR TITLE
remove gcdump support

### PR DESCRIPTION
**Pull request by suwatch**
VS team stops supporting gcdump, hence so do we.   I have separate bug to track removing it from the  binary from webpi feed.

### CODE REVIEW

**Comment by davidebbo** [comment]
:shipit:

**Comment by albertjan** [comment]
How are we supposed to do this now? :smile:

**Comment by davidebbo** [comment]
The feature had very low usage in VS and is getting deprecated. Not that regular dumps are still available.

**Comment by albertjan** [comment]
I understand, we solved it by running our application locally, I never needed the feature before but it would have saved us some time today:smile:.

**Pull request merged**
