### PR TITLE
[DebugConsole] Added new file button and toast notifications for errors

### PR DESCRIPTION
**Pull request by snobu**
### Added **New File** button:
newfile

<br><br>
### Added toast notifications for backend calls that return error:
toast

<br><br>
#### You can select the text and dismiss selectively:
select-in-toast

<br><br>
#### Works in the editor as well:
ace-with-toast

<br><br>
### Added a few __azure__ color accents:
accent

<br>
#### And the cursor:
console-cursor

### CODE REVIEW

**Comment by davidebbo** [comment]
@snobu I just gave this a try in a private site extension on Azure, and I can't get New File to work. e.g.

- Go into `site` folder
- Click + and choose 'New File'

Result: it never pops up the field to type the filename, and instead just quietly takes me back to `d:\home`.

**Comment by davidebbo** [comment]
Looks like this works on Edge, but not Chrome. Likewise the error toast notification worked for Edge and not Chrome.

**Comment by snobu** [comment]
Hmm.. what you're describing is a case of aggressive caching of Filebrowser.js (where all the newfile logic resides).

I've deployed the `snobu-toast` branch to a new Web App and did the exact tests you did:

toast1

toast2

toast3



I've also tested inside __/site__ and made sure the files were created on disk.

**Comment by davidebbo** [comment]
Indeed, it was a refresh issue for my site in Chrome! It does seem to work well :)

**Comment by ahmelsayed** [comment]
looks great!

**Pull request merged**
