### PR TITLE
Adding UI for Zip Deploy

### PR DESCRIPTION
**Pull request by nmallick1**
Adding a UI for Zip Deploy and a link to this UI under Tools menu. For some reason this PR is also picking up the commit for bug 2546. Not sure if I am doing something wrong, this should have already been committed.

### CODE REVIEW

**Comment by davidebbo** [comment]
About it picking up unwanted changes, you probably just need to rebase your work over the latest.

I tried your change, and one issue I ran into is that the file list doesn't update after I do a deployment, and more generally doesn't update when file changes happen. Shouldn't that work the same way as the regular console?

**Comment by nmallick1** [comment]
It should update just the same way.. I never checked part as I was working against local copy for JS and figured it wont work anyways.. Ill check and resubmit with changes.

Regards,

Nazeef Mallick
________________________________

**Comment by nmallick1** [comment]
Fixed the issue where the file list wasn't updating. Also, found and fixed another bug in TreeView where when the AutoRefresh happens while switching from temp deploymentID to actual decploymentID, the view ran into an inconsistent state and was erroring out. Kindly check.

**Comment by davidebbo** [comment]
@nmallick1 I'm still not having any luck with the file list update. e.g.

- I start empty
- I drop a small zip with two files. I see all the deployment logs but no files show up
- I refresh the whole page and they show up

Does this same scenario work for you?

**Comment by nmallick1** [comment]
Yes it does.. Let me check which version of the file got checked in.. I tested in chrome and IE

Regards,

Nazeef Mallick
________________________________

**Comment by nmallick1** [comment]
I tested once again with the files that I have and it is working for me. I did a rebase of my project right after creating the Pull Request, not sure if that has something to do with it. Let me delete the pull request and create a new one.

**Comment by nmallick1** [comment]
Closing this Pull Request, will create a new one

**Comment by davidebbo** [comment]
Ok, make sure you do a rebase and not a merge. Should be as simple as `git rebase upstream master` (assuming you set `upstream` to the main repo).

**Pull request closed without merging**
