### PR TITLE
Return 200 instead of 202 when running WebJobs from ARM

### PR DESCRIPTION
**Pull request by davidebbo**
See comment in code

### CODE REVIEW

**Comment by suwatch** [comment]
:shipit:

**Comment by mathewc** [comment]
It'd be best if we had a regression test for this in place - that sends a mocked request that looks like an ARM request and verifies the behavior. Is there already a test suite that you could add one to?

**Comment by davidebbo** [comment]
Afaik, we don't currently have any tests that exercise the ARM code path. Maybe others know otherwise?

**Comment by mathewc** [comment]
There is a `JobsControllerTests` test suite that is already doing some unit tests mocking requests and verifying behavior. It should be easy to add a new test that sends a request with/without the ARM header and verifies the response code. We have some other tests that mock ARM requests, e.g `SiteExtensionInstallUninstallAsyncTest`

**Comment by davidebbo** [comment]
Added ARM test: 0c73e75d3228b923a96511ed002799e92783f069

**Comment by mathewc** [comment]
Awesome, thanks :)

**Pull request merged**
