### PR TITLE
Update DeterminePrimaryScriptFile implementation

### LINKED ISSUE #3116: [Functions]Keep implementation of DeterminePrimaryScriptFile in sync with host
original issue #https://github.com/Azure/azure-functions-host/issues/5587

Implementation of `DeterminePrimaryScriptFile` is updated in the host. Need to keep them in sync

### PR DESCRIPTION
**Pull request by pragnagopa**
Fixes #3116

### CODE REVIEW

**Comment by pragnagopa** [comment]
cc @Hazhzeng @ankitkumarr

**Comment by Hazhzeng** [comment]
@suwatch Please take a look at this PR

**Comment by suwatch** [comment]
@ankitkumarr  and @pragnagopa  please review and sign off.  I can merge it after.

**Comment by pragnagopa** [comment]
@ankitkumarr - can please review?

**Pull request merged**
