### PR TITLE
Added check to LibGit2SharpRepository to see if we are checking out a…

### PR DESCRIPTION
**Pull request by danlister**
… tag instead of a branch #1435 

To deploy a tag, the branch name passed to the function must start with "refs/tags/". From there, we can assume we want to deploy a tag instead of a branch. After testing locally, it seemed to work okay. I was able to deploy a master branch for example to Kudu, change the deployment source to a tag, create a tag locally, push to Kudu and see a successful deployment of the tag reference.

I also then created further commits on the master branch and pushed to Kudu. The tag reference was only ever deployed and not the further commits. My last test was to delete and re-create a tag, pushing to Kudu after. The deployment for the application deployed the updated tag reference.

I imagine I've not covered all bases but it's a start (I hope)

### CODE REVIEW

**Comment by davidebbo** [comment]
Didn't get to play with it much, but the change seems unlikely to regress anything given the conditional. We should add coverage though.

Thanks for your contrib!

**Comment by davidebbo** [comment]
@danlister this is now deployed. Can you give it a try in Azure and make sure everything works as you expect? Thanks!

**Comment by danlister** [comment]
@davidebbo It seems to work as expected. Below were my test steps:

- Navigate to a Web App on management.azure.com
- Change the "Branch to Deploy" configuration property to a tag
- Navigate back to portal.azure.com
- Re-deploy the App Service

**Comment by davidebbo** [comment]
Perfect, thanks!

**Pull request merged**
