### PR TITLE
Replaced ajax spinner with Kudu PaKman gif

### PR DESCRIPTION
**Pull request by snobu**
Related to https://github.com/projectkudu/kudu/pull/1816

### /DebugConsole ###
pakmanpull1

##### /w file transfer: #####
pakmanpull12

### /ProcessExplorer ###
pe

Test site: `https://kududev.scm.azurewebsites.net/basicauth`
Kudu Devs, search for the test site in your Outlook inbox, credentials are in there.

### CODE REVIEW

**Comment by davidebbo** [comment]
Kudu has officially jumped the shark now ;)

**Comment by mathewc** [comment]
Fonzi

**Comment by snobu** [comment]
Happy new year!
jump

**Comment by davidebbo** [comment]
Where is my shark fin soup?

**Comment by snobu** [comment]
This is getting out of control. GREENPEACE might want to have a word with us.

**Pull request merged**
