### PR TITLE
FIXED: #1492, should not see or install unlisted packages

### PR DESCRIPTION
**Pull request by shrimpy**

### CODE REVIEW

**Comment by ahmelsayed** [comment]
:shipit:

**Comment by davidebbo** [comment]
Copying my comment from the issue:

I think the desired behavior here should be the same as with NuGet.exe:
- if no version is passed in, you the latest that's not unlisted
- if a version is passed in, honor it regardless of whether it's listed or unlisted

Is that how your change works? Looking at the code, I'm not so sure.

**Comment by shrimpy** [comment]
current code change will not look from unlisted package. 
tried with Nuget.exe, it won`t list any unlisted package, but do allow user to install package that is "unlisted"

updating logic to do similar behavior. will have code update soon.

**Comment by shrimpy** [comment]
@davidebbo sent out another PR to address your comment https://github.com/projectkudu/kudu/pull/1494, please review

**Pull request merged**
