### PR TITLE
kudu favicon ftw!

### PR DESCRIPTION
**Pull request by kenegozi**

### CODE REVIEW

**Comment by davidebbo** [comment]
Good catch! Had to add it to csproj as well.

**Comment by kenegozi** [comment]
lol half a year away from .NET and I totally forgot about csproj and not automatically including everything in the folder structure.

**Comment by davidebbo** [comment]
I haven't been away at all, and I still messed it up! https://github.com/projectkudu/kudu/commit/394df9b423cba6c8c7cc659baa827ea33834feb7

**Comment by davidebbo** [comment]
One thing I just noticed is that the favicon ends up also applying to the WebJobs dashboard (or any site extension), since it's hosted in the scm site. A bit quirky but no big deal. Is it even possible to override the favicon for a sub path?

**Pull request closed without merging**
