### PR TITLE
Allow static deployments outside of wwwroot with backwards compatibility

### PR DESCRIPTION
**Pull request by dannysongg**
### Overview
Now allow static files to by deployed outside of wwwroot while maintaining backwards compatibility with the old behavior.

### Spec
Target-Path always are relative to `"/site/wwwroot/"` if it doesn't start with a magic word (see point no. 2)
Example:
`path="foo/bar.txt"`
`path="/foo/bar.txt"`

If Target-Path starts with any of the following magic words:
`"home", "%home%", "$home", "/home", "/%home%", /$home"`
In this case, the magic word will be replaced by "/" and it will be relative to the root.
Example:
`path="/home/site/test/test.xml"`
Action:
The test.xml file will be deployed at `"/site/test/test.xml"`

Clean=true will always clean the following folders:
- Content Folder (/site/wwwroot/)
- Scripts folder
- Lib folder

### Tested Cases

- path=test.xml
- path=test2.xml&clean=true
- path=a/test.xml
- path=b/test.xml&clean=true
- path=/home/site/wwwroot/test.xml
- path=/home/site/wwwroot/test.xml&clean-=true
- path=/home/site/wwwroot/a/test.xml
- path=/home/site/wwwroot/b/test.xml&clean-=true
- path=/home/test.xml
- path=/home/test.xml&clean=true
- path=/home/a/test.xml
- path=/home/a/test.xml&clean=true

### CODE REVIEW

**Comment by dannysongg** [comment]
@jvano @dfuenzalida @gregorygoldshteyn @caovicto

**Review by dfuenzalida — APPROVED** [review]

**Review by jvano — APPROVED** [review]
Looks good! :shipit:

**Comment by suwatch** [comment]
@jvano  and @dannysongg  let me know if this is ready to be merged - I can do that

**Comment by dannysongg** [comment]
@suwatch this change is ready to be merged!

**Pull request merged**
