### PR TITLE
[DebugConsole] Fix upload progress indicator

### LINKED ISSUE #2266: [DebugConsole] Upload progress bar broken
The DebugConsole upload progress indicator seems to no longer work.

To repro: Upload a large file via drag-and-drop, click the progress indicator -> the progress bar stays at 0%.

Browser console:

```
SCRIPT5022: Unable to parse bindings.
Message: SyntaxError: Expected ':';
Bindings value:  style
                                                 { width $root.getCopyPercentage($parent.copyProgStats()[item]) + '%' } , css { 'progress-bar-info'
                                                 $root.getCopyPercentage($parent.copyProgStats()[item]) < 100, 'progress-bar-success': $root.getCopyPercentage($parent.copyProgStats()[item]) >= 100  }, text: $root.getCopyPercentageDisplay($parent.copyProgStats()[item])
knockout-2.2.1.js (5,28)
```

This probably happened here:
https://github.com/projectkudu/kudu/commit/41835558895f37dbb0efb30fe6b420e99b320388#diff-07d92cee177630927569cbad46591ec8R126

There should be a `:` after `width` in `{ width $root.getCopyPercentage($parent.copyProgStats()[item])...`

### PR DESCRIPTION
**Pull request by snobu**
Fixes #2266 (File upload progress indicator).

### CODE REVIEW

**Comment by snobu** [comment]
@badescuga Where's the double slash coming from? We should fix that too while we're at it.

image

**Comment by badescuga** [comment]
Don't remember that being there. Could be just a typo as i remember altering the path for display purposes.

**Comment by snobu** [comment]
I can't find where you construct that path in the code.. Can you point me to the exact line?

**Comment by badescuga** [comment]
i worked on this more than a year ago, so i can't remember right now. I might look at it tomorrow/after vacation.

**Comment by snobu** [comment]
This can be merged as-is for now.

**Comment by davidebbo** [comment]
@snobu Did we never merge that in? Is it still ready to go?

**Comment by snobu** [comment]
We didn't. It's ready to go. Fixes the upload progress indicator that broke during the `WindowsConsole/LinuxConsole.cshtml` split.

**Pull request merged**
