### PR TITLE
Fix logo height issue with edge 13

### PR DESCRIPTION
**Pull request by shibayan**
Issue with Edge 13 (Windows 10 TH2) And I think the Edge of the problem...

kudu_logo

### CODE REVIEW

**Comment by davidebbo** [comment]
Yes, I see the issue as well with my TH2 box.

Have you tested that things still look the same in Chrome/IE with the fix? If so, it should be good to go.

**Comment by shibayan** [comment]
Yes. I deployed private kudu on Web Apps and confirmed the display in IE / Chrome.

kudu_chrome

**Comment by davidebbo** [comment]
Thanks!

**Comment by davidebbo** [comment]
The change is now live in Azure.

**Pull request merged**
