### PR TITLE
RFC: Binding objects in UI instead of strings to display more accurate binding information, should fix #1521

### LINKED ISSUE #1521: Application and Service link shows as http://localhost:XXXX/
I have deploy kudu on our dev web server.
Everytime I create a new application the urls displayed on the dashboard contains localhost such as

Application URL
http://localhost:47793/
This is the link to your website.

Service URL
http://localhost:5306/
This is the link to the kudu service.

How can I have an IP or Host name used.

I cannot use the urlBaseValue as I have no DNS and I do not want to update all the devs host files.

I can copy past the url from the dashboard and replace the host with the IP and this works. but I want to have valid values displayed on the page.

Thanks for any help.

### PR DESCRIPTION
**Pull request by jeme**
Also added DNS host name for formatting URLS for more external use, should fix #1521

I am getting an error when I run code analasis from Visual Studio at https://github.com/projectkudu/kudu/blob/master/Kudu.Core/SiteExtensions/SiteExtensionStatus.cs#L143 which I don't have any changes to. So it must also be in the main branch...

Just a FYI, the build.cmd doesn't give me that error.

### CODE REVIEW

**Comment by davidebbo** [comment]
Sorry, closed by mistake

**Comment by davidebbo** [comment]
The closing happened as a result of me mistakenly deleting the master branch (oops!), which closed all the PRs.

**Comment by jeme** [comment]
""The closing happened as a result of me mistakenly deleting the master branch (oops!),""

o.O...

**Comment by mi-hol** [comment]
@jeme @davidebbo ' closed in error Sep 25, 2015' is it still required?

**Comment by jeme** [comment]
@mi-hol I must admit, I have not had the time to keep up with the project, so I don't know if the issue this solves (#1521) was solved in another way.

At the same time I sadly won't have the time to rework it any time soon either. 

I have so much on the TODO and Kudu things are sadly way down the list.

**Comment by davidebbo** [comment]
Thanks @jeme for following up. Closing this PR.

**Pull request closed without merging**
