### PR TITLE
change the max file limit to 300, issue #2226

### PR DESCRIPTION
**Pull request by watashiSHUN**

### CODE REVIEW

**Comment by davidebbo** [comment]
:shipit:

**Comment by davidebbo** [comment]
Merged.

**Comment by ericpberry** [comment]
I see from the code that this limit can be overridden by adding a 'maxViewItems' key and value to your browser's localStorage.  This was very useful for us.  It might worth documenting in the wiki.

**Comment by davidebbo** [comment]
@ericpberry Good point! I just added to wiki: https://github.com/projectkudu/kudu/wiki/Kudu-console#navigate-around-using-the-folder-ui

**Pull request closed without merging**
