### PR TITLE
[WIP] Upgrade to LibGit2Sharp where that makes sense

### PR DESCRIPTION
**Pull request by nulltoken**
Opened early for your pleasure and your feedback!

### CODE REVIEW

**Comment by ahmelsayed** [comment]
Hi @nulltoken I'm taking a look at merging this pull request. 
I am making some changes to switch over more functions to use LibGit2Sharp and also allowing a mode where the old git.exe code path will be the same.
I have few questions about LibGit2Sharp.

what would be the equivalent of 
```
git init .
git remote add -t master external "http://github.com/repo/repo.git"
git fetch external
```

I tried 
```C#
var dotGitPath = LibGit2Sharp.Repository.Init(RepositoryPath);
using (var repo = new LibGit2Sharp.Repository(dotGitPath))
{
    repo.Network.Remotes.Add("external", "http://github.com/repo/repo.git");
    var localBranch = repo.Branches["master"]; // This is always null!
    if (localBranch == null)
    {
        localBranch = repo.CreateBranch("master"); //This throws LibGit2Sharp.UnbornBranchException
    }
    var remoteBranch = repo.Branches["external/master"]
    repo.Branches.Update(localBranch, b => b.TrackingBranch = remoteBranch.CanonicalName);
}
```
that doesn't work. It's probably something obvious that I am missing!

second question, I am trying to replace `git ls-files` with this
```C#
using (var repo = new LibGit2Sharp.Repository(RepositoryPath))
{
    var files = repo.Index.Where(i => lookupList.Contains(i.Path, StringComparer.OrdinalIgnoreCase))
                                      .Select(i => Path.Combine(RepositoryPath, i.Path))
                                      .Where(p => p.StartsWith(path, StringComparison.OrdinalIgnoreCase));
}
```

but it's throwing 
```C#
Safe handle has been closed
System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
	   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
	   at LibGit2Sharp.Core.NativeMethods.git_index_entrycount(IndexSafeHandle index)
	   at LibGit2Sharp.Core.Proxy.git_index_entrycount(IndexSafeHandle index)
	   at LibGit2Sharp.Index.get_Count()
	   at LibGit2Sharp.Index.AllIndexEntries()
	   at LibGit2Sharp.Index.GetEnumerator()
	   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
	   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

And last question, I'm not sure looking at the LibGit2Sharp wiki if it can be used to replace a git.exe server implementation or not. I see this open issue https://github.com/libgit2/libgit2sharp/issues/90 but I am not entirely sure what's smart HTTP.

**Comment by nulltoken** [comment]
@ahmelsayed Thanks for this. Below some thoughts about the topics.

>what would be the equivalent of
>
>```
>git init .
>git remote add -t master external "http://github.com/repo/repo.git"
>git fetch external
>```

I'd go with

```csharp
var gitDirPath = Repository.Init(path);
using (var repo = new Repository(gitDirPath))
{
    string trackedBranchName = string.Format("{0}/{1}", remoteName, branchName);
    string refSpec = string.Format("+refs/heads/{0}:refs/remotes/{1}", branchName, trackedBranchName);

    // Configure the remote
    Remote remote = repo.Network.Remotes.Add(remoteName, url, refSpec);

    // This will only retrieve the "master"
    repo.Network.Fetch(remote);

    // Optionally set up the branch tracking configuration
    Branch trackedBranch = repo.Branches[trackedBranchName];
    Branch branch = repo.CreateBranch(branchName, trackedBranch.Tip);
    repo.Branches.Update(branch,
        b => b.TrackedBranch = trackedBranch.CanonicalName);
}
```

>second question, I am trying to replace git ls-files with this

There are good chances you leverage the `files` variable outside of the scope of the repository. This should not throw if you materialize the result of the deferred linq request through a `ToList()` call for instance.

**Comment by nulltoken** [comment]
>And last question, I'm not sure looking at the LibGit2Sharp wiki if it can be used to replace a git.exe server implementation or not. I see this open issue libgit2/libgit2sharp#90 but I am not entirely sure what's smart HTTP.

see and http://git-scm.com/search/results?search=smart https://github.com/git/git/tree/master/Documentation/technical for more details. LibGit2Sharp is not ready yet for this as explained by @carlosmn in libgit2/libgit2sharp#90. If you're willing to work in this area, we'll be very happy to support you and help you make this happen!

BTW, would you have additional "how to/programming related" LibGit2Sharp questions, would you please be so kind as to ask them over at StackOverflow? We closely monitor the *libgit2sharp* and will promptly answer them there.

Indeed, we've found out that SO is far more googl'able/bing'able than GitHub and favor it for this purpose.

**Comment by ahmelsayed** [comment]
Thank you very much. I will take a look at that and make sure to ask any further questions on SO.

**Comment by nulltoken** [comment]
:heart_eyes: 

One final nitpick, though, regarding

```
using (var repo = new LibGit2Sharp.Repository(RepositoryPath))
{
    var files = repo.Index.Where(i => lookupList.Contains(i.Path, StringComparer.OrdinalIgnoreCase))
                                      .Select(i => Path.Combine(RepositoryPath, i.Path))
                                      .Where(p => p.StartsWith(path, StringComparison.OrdinalIgnoreCase));
}
```

Rather than reusing `RepositoryPath`, I'd tend to use `repo.Info.Workdir` (although I'm not sure to completely understand the `Where` clause)

**Comment by ahmelsayed** [comment]
Thanks I'll make the change and keep that in mind.
The first Where clause is actually functionally wrong. it's supposed to replace `git ls-files {lookupList}` but it's of course wrong because `lookupList` actually contains wildcards like `*.csproj` and `*.sln` I still have to fix that. 

The second Where clause is a direct translation of [this](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/SourceControl/Git/GitExeRepository.cs#L414-L416) where `path` is a subfolder in the repo that we are searching in.

**Comment by nulltoken** [comment]
@ahmelsayed I'm not actually sure to understand what you're doing with `ListFiles`. What are you trying to achieve?

**Comment by ahmelsayed** [comment]
`ListFiles` is used to look for certain files in the repo e.g. .sln, .csproj. The context is here https://github.com/projectkudu/kudu/issues/607 but basically we used to look for these files recursively in the workingDirectory of the repo, but we sometimes get humongous workingDirectories for relatively simple repos due to npm modules, build artifacts, etc. So we switched the search to use `git ls-files` since git knows about all the tracked files, doing `git ls-files *.sln` is a lot faster than using `System.IO` to look through the files.

**Comment by nulltoken** [comment]
Couldn't you use 

```
public virtual T Compare<T>(IEnumerable<string> paths = null, bool includeUntracked = false, ExplicitPathsOptions explicitPathsOptions = null,
            CompareOptions compareOptions = null) where T : class
```

IIRC the paths accepts wildcards.

See https://github.com/libgit2/libgit2sharp/pull/907/files#diff-2 for an example of a diff comparison between the workdir and the index.

**Comment by ahmelsayed** [comment]
`Diff.Compare` will only return files if they have changed, right?

In this scenario the files haven't changed, the scenario is:
1. We just got a repo of a .NET project and built it.
2. We end up with a really large git working directory because of all the build artifacts.
3. We want to search the repo for *.sln files so we use `git ls-files *.sln`
when I tried `Diff.Compare<TreeChanges>` paths does take wildcards, but it will only return files that match the pattern if they have changed
Did I misunderstand your suggestion?

**Comment by nulltoken** [comment]
>Diff.Compare will only return files if they have changed, right?

Not only. See https://github.com/libgit2/libgit2sharp/blob/vNext/LibGit2Sharp/CompareOptions.cs#L39.

If you're only interested in searching the index content, you may use a different overload and compare against a null Tree, which won't involve hitting the file system.

```
var patch2 = repo.Diff.Compare<TreeChanges>(null,
    DiffTargets.Index,
        compareOptions: new CompareOptions { IncludeUnmodified = false, Similarity = SimilarityOptions.None },
        paths: new [] { "*.txt" });
``

**Comment by ahmelsayed** [comment]
That works perfectly! Thank you very much again. Really appreciate the help :)

**Comment by nulltoken** [comment]
@ahmelsayed With a great pleasure. Feel free to notify me in your PRs would you like an additional pair of eyes when it comes to LibGit2Sharp.

**Comment by nulltoken** [comment]
@ahmelsayed FWIW, I've glanced at https://github.com/projectkudu/kudu/commit/21749fc3848b7c876314d9d67fd6cadbf276a206

If you opened a PR, I think I could already propose some improvements ;-)

**Comment by ahmelsayed** [comment]
:) Cool! There are still few failing test cases that I need to fix and general clean-ups to perform. 
I ping you as soon as I open a PR. Again thanks for all the help :+1:

**Comment by nulltoken** [comment]
Superseded by #1440

**Pull request closed without merging**
