### PR TITLE
Fix for Nuget search which only gets extensions from page 1.

### PR DESCRIPTION
**Pull request by khkh-ms**
It will get the search results from other pages as well.

### CODE REVIEW

**Comment by suwatch** [comment]
@khkh-ms  they look good to me - let me know if you have one of your team member to sign off and I can rebase and merge

**Comment by patelchandni** [comment]
@khkh-ms looks good to me as well.

**Review by patelchandni — COMMENTED** [review]
@khkh-ms looks good to me as well.

**Comment by khkh-ms** [comment]
Thanks @patelchandni ! @suwatch, do you want me to merge it?

**Pull request merged**
